#server.port=8089

spring.application.name=WeatherForecast

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Database connection properties (already in your file)
spring.datasource.url=jdbc:postgresql://localhost:5433/weatherdb
spring.datasource.username=postgres
spring.datasource.password=password

weather.api.key=e912bfc9729a8e39d04c5350f1b1e0d7

# Javers Configuration
javers.commitIdGenerator=synchronized_sequence

# Additional Javers Configuration for PostgreSQL
javers.sqlSchema=public

javers.algorithm=simple
javers.mappingStyle=field
javers.newObjectSnapshot=true
javers.prettyPrint=true
javers.sqlSchemaManagementEnabled=false
javers.spring-data.enabled=true

# Logging
logging.level.org.springframework=DEBUG
logging.level.org.javers=DEBUG
logging.level.com.example.WeatherForecast=DEBUG

logging.level.com.fasterxml.jackson.databind=DEBUG


